package io.gongarce.ud2_components_example;

import io.gongarce.ud2_components.state_label.State;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Gonzalo
 */
public class FrameWithStateLabel extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FrameWithStateLabel
     */
    public FrameWithStateLabel() {
        initComponents();
        this.setLocationRelativeTo(null);

        lblState.setText("State: Default");
        radioDefault.setSelected(true);

        radioDefault.addActionListener(this);
        radioError.addActionListener(this);
        radioSuccess.addActionListener(this);
        radioWarning.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        radioGroupState = new javax.swing.ButtonGroup();
        lblState = new io.gongarce.ud2_components.state_label.StateLabel();
        radioDefault = new javax.swing.JRadioButton();
        radioSuccess = new javax.swing.JRadioButton();
        radioWarning = new javax.swing.JRadioButton();
        radioError = new javax.swing.JRadioButton();
        companyLogo2 = new io.gongarce.ud2_components.company_logo.CompanyLogo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblState.setState(io.gongarce.ud2_components.state_label.State.DEFAULT);
        lblState.setText("stateLabel2");
        lblState.setTextColor(new java.awt.Color(0, 102, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 20;
        getContentPane().add(lblState, gridBagConstraints);

        radioGroupState.add(radioDefault);
        radioDefault.setSelected(true);
        radioDefault.setText("Default");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(radioDefault, gridBagConstraints);

        radioGroupState.add(radioSuccess);
        radioSuccess.setText("Success");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(radioSuccess, gridBagConstraints);

        radioGroupState.add(radioWarning);
        radioWarning.setText("Warning");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(radioWarning, gridBagConstraints);

        radioGroupState.add(radioError);
        radioError.setText("Error");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(radioError, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(companyLogo2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameWithStateLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameWithStateLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameWithStateLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameWithStateLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameWithStateLabel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private io.gongarce.ud2_components.company_logo.CompanyLogo companyLogo2;
    private io.gongarce.ud2_components.state_label.StateLabel lblState;
    private javax.swing.JRadioButton radioDefault;
    private javax.swing.JRadioButton radioError;
    private javax.swing.ButtonGroup radioGroupState;
    private javax.swing.JRadioButton radioSuccess;
    private javax.swing.JRadioButton radioWarning;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioDefault.isSelected()) {
            lblState.setText("State: Default");
            lblState.setState(State.DEFAULT);
        } else if (radioError.isSelected()) {
            lblState.setText("State: Error");
            lblState.setState(State.ERROR);
        } else if (radioSuccess.isSelected()) {
            lblState.setText("State: Success");
            lblState.setState(State.SUCCESS);
        } else if (radioWarning.isSelected()) {
            lblState.setText("State: Warning");
            lblState.setState(State.WARNING);
        }
    }
}
